development:
  adapter: mysql2
  encoding: utf8
  database: reader_dev
  username: root
  password: 
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  database: reader_test
  username: root
  password:
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  database: reader_prod
  username: root
  password: 
  host: 127.0.0.1
